// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Rock_paper_and_scissors_Game
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 MyProperty;
    }
}
